export const CONTACT_CREATE_REQUEST = 'CONTACT_CREATE_REQUEST';
export const CONTACT_CREATE_SUCCESS = 'CONTACT_CREATE_SUCCESS';
export const CONTACT_CREATE_FAIL = 'CONTACT_CREATE_FAIL';
export const CONTACT_CREATE_RESET = 'CONTACT_CREATE_RESET';

export const CONTACT_DETAILS_REQUEST = 'CONTACT_DETAILS_REQUEST';
export const CONTACT_DETAILS_SUCCESS = 'CONTACT_DETAILS_SUCCESS';
export const CONTACT_DETAILS_FAIL = 'CONTACT_DETAILS_FAIL';

export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';

export const CONTACT_TRASH_LIST_REQUEST = 'CONTACT_TRASH_LIST_REQUEST';
export const CONTACT_TRASH_LIST_SUCCESS = 'CONTACT_TRASH_LIST_SUCCESS';
export const CONTACT_TRASH_LIST_FAIL = 'CONTACT_TRASH_LIST_FAIL';

export const CONTACT_REPLY_REQUEST = 'CONTACT_REPLY_REQUEST';
export const CONTACT_REPLY_SUCCESS = 'CONTACT_REPLY_SUCCESS';
export const CONTACT_REPLY_FAIL = 'CONTACT_REPLY_FAIL';

export const CONTACT_STATUS_REQUEST = 'CONTACT_STATUS_REQUEST';
export const CONTACT_STATUS_SUCCESS = 'CONTACT_STATUS_SUCCESS';
export const CONTACT_STATUS_FAIL = 'CONTACT_STATUS_FAIL';
export const CONTACT_STATUS_RESET = 'CONTACT_STATUS_RESET';

export const CONTACT_DELETE_REQUEST = 'CONTACT_DELETE_REQUEST';
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS';
export const CONTACT_DELETE_FAIL = 'CONTACT_DELETE_FAIL';
export const CONTACT_DELETE_RESET = 'CONTACT_DELETE_RESET';

export const CONTACT_DESTROY_REQUEST = 'CONTACT_DESTROY_REQUEST';
export const CONTACT_DESTROY_SUCCESS = 'CONTACT_DESTROY_SUCCESS';
export const CONTACT_DESTROY_FAIL = 'CONTACT_DESTROY_FAIL';
export const CONTACT_DESTROY_RESET = 'CONTACT_DESTROY_RESET';

export const CONTACT_RESTORE_REQUEST = 'CONTACT_RESTORE_REQUEST';
export const CONTACT_RESTORE_SUCCESS = 'CONTACT_RESTORE_SUCCESS';
export const CONTACT_RESTORE_FAIL = 'CONTACT_RESTORE_FAIL';
export const CONTACT_RESTORE_RESET = 'CONTACT_RESTORE_RESET';
