export const IMAGES = 'IMAGES';
export const SET_IMAGE = 'SET_IMAGE';

export const IMAGE_STATUS_REQUEST = 'IMAGE_STATUS_REQUEST';
export const IMAGE_STATUS_SUCCESS = 'IMAGE_STATUS_SUCCESS';
export const IMAGE_STATUS_FAIL = 'IMAGE_STATUS_FAIL';
export const IMAGE_STATUS_RESET = 'IMAGE_STATUS_RESET';

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS';
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL';
export const IMAGE_DELETE_RESET = 'IMAGE_DELETE_RESET';

export const IMAGE_DESTROY_REQUEST = 'IMAGE_DESTROY_REQUEST';
export const IMAGE_DESTROY_SUCCESS = 'IMAGE_DESTROY_SUCCESS';
export const IMAGE_DESTROY_FAIL = 'IMAGE_DESTROY_FAIL';
export const IMAGE_DESTROY_RESET = 'IMAGE_DESTROY_RESET';

export const IMAGE_RESTORE_REQUEST = 'IMAGE_RESTORE_REQUEST';
export const IMAGE_RESTORE_SUCCESS = 'IMAGE_RESTORE_SUCCESS';
export const IMAGE_RESTORE_FAIL = 'IMAGE_RESTORE_FAIL';
export const IMAGE_RESTORE_RESET = 'IMAGE_RESTORE_RESET';
