export const POSTS_LIST = 'POSTS_LIST';
export const SET_POST = 'SET_POST';

export const POST_STATUS_REQUEST = 'POST_STATUS_REQUEST';
export const POST_STATUS_SUCCESS = 'POST_STATUS_SUCCESS';
export const POST_STATUS_FAIL = 'POST_STATUS_FAIL';
export const POST_STATUS_RESET = 'POST_STATUS_RESET';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';
export const POST_DELETE_RESET = 'POST_DELETE_RESET';

export const POST_DESTROY_REQUEST = 'POST_DESTROY_REQUEST';
export const POST_DESTROY_SUCCESS = 'POST_DESTROY_SUCCESS';
export const POST_DESTROY_FAIL = 'POST_DESTROY_FAIL';
export const POST_DESTROY_RESET = 'POST_DESTROY_RESET';

export const POST_RESTORE_REQUEST = 'POST_RESTORE_REQUEST';
export const POST_RESTORE_SUCCESS = 'POST_RESTORE_SUCCESS';
export const POST_RESTORE_FAIL = 'POST_RESTORE_FAIL';
export const POST_RESTORE_RESET = 'POST_RESTORE_RESET';
