export const SET_USERS = 'SET_USERS';
export const SET_USER = 'SET_USER';
export const SET_ROLE = 'SET_ROLE';
export const REMOVE_USER = 'REMOVE_USER';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const RESET_MESSAGE = 'RESET_MESSAGE';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const USER_DESTROY_REQUEST = 'USER_DESTROY_REQUEST';
export const USER_DESTROY_SUCCESS = 'USER_DESTROY_SUCCESS';
export const USER_DESTROY_FAIL = 'USER_DESTROY_FAIL';
export const USER_DESTROY_RESET = 'USER_DESTROY_RESET';

export const USER_RESTORE_REQUEST = 'USER_RESTORE_REQUEST';
export const USER_RESTORE_SUCCESS = 'USER_RESTORE_SUCCESS';
export const USER_RESTORE_FAIL = 'USER_RESTORE_FAIL';
export const USER_RESTORE_RESET = 'USER_RESTORE_RESET';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const USER_INFO_RESET = 'USER_INFO_RESET';
