export const VOUCHER_LIST_REQUEST = 'VOUCHER_LIST_REQUEST';
export const VOUCHER_LIST_SUCCESS = 'VOUCHER_LIST_SUCCESS';
export const VOUCHER_LIST_FAIL = 'VOUCHER_LIST_FAIL';

export const VOUCHER_LIST_TRASH_REQUEST = 'VOUCHER_LIST_TRASH_REQUEST';
export const VOUCHER_LIST_TRASH_SUCCESS = 'VOUCHER_LIST_TRASH_SUCCESS';
export const VOUCHER_LIST_TRASH_FAIL = 'VOUCHER_LIST_TRASH_FAIL';

export const VOUCHER_DETAILS_REQUEST = 'VOUCHER_DETAILS_REQUEST';
export const VOUCHER_DETAILS_SUCCESS = 'VOUCHER_DETAILS_SUCCESS';
export const VOUCHER_DETAILS_FAIL = 'VOUCHER_DETAILS_FAIL';
export const VOUCHER_DETAILS_RESET = 'VOUCHER_DETAILS_RESET';

export const VOUCHER_DELETE_REQUEST = 'VOUCHER_DELETE_REQUEST';
export const VOUCHER_DELETE_SUCCESS = 'VOUCHER_DELETE_SUCCESS';
export const VOUCHER_DELETE_FAIL = 'VOUCHER_DELETE_FAIL';
export const VOUCHER_DELETE_RESET = 'VOUCHER_DELETE_RESET';

export const VOUCHER_RESTORE_REQUEST = 'VOUCHER_RESTORE_REQUEST';
export const VOUCHER_RESTORE_SUCCESS = 'VOUCHER_RESTORE_SUCCESS';
export const VOUCHER_RESTORE_FAIL = 'VOUCHER_RESTORE_FAIL';
export const VOUCHER_RESTORE_RESET = 'VOUCHER_RESTORE_RESET';

export const VOUCHER_DESTROY_REQUEST = 'VOUCHER_DESTROY_REQUEST';
export const VOUCHER_DESTROY_SUCCESS = 'VOUCHER_DESTROY_SUCCESS';
export const VOUCHER_DESTROY_FAIL = 'VOUCHER_DESTROY_FAIL';
export const VOUCHER_DESTROY_RESET = 'VOUCHER_DESTROY_RESET';

// export const VOUCHER_PAY_REQUEST = 'VOUCHER_PAY_REQUEST';
// export const VOUCHER_PAY_SUCCESS = 'VOUCHER_PAY_SUCCESS';
// export const VOUCHER_PAY_FAIL = 'VOUCHER_PAY_FAIL';
// export const VOUCHER_PAY_RESET = 'VOUCHER_PAY_RESET';

// export const VOUCHER_STATUS_REQUEST = 'VOUCHER_STATUS_REQUEST';
// export const VOUCHER_STATUS_SUCCESS = 'VOUCHER_STATUS_SUCCESS';
// export const VOUCHER_STATUS_FAIL = 'VOUCHER_STATUS_FAIL';
// export const VOUCHER_STATUS_RESET = 'VOUCHER_STATUS_RESET';

// export const VOUCHER_DELIVERED_REQUEST = 'VOUCHER_DELIVERED_REQUEST';
// export const VOUCHER_DELIVERED_SUCCESS = 'VOUCHER_DELIVERED_SUCCESS';
// export const VOUCHER_DELIVERED_FAIL = 'VOUCHER_DELIVERED_FAIL';
// export const VOUCHER_DELIVERED_RESET = 'VOUCHER_DELIVERED_RESET';

// export const VOUCHER_MINE_LIST_REQUEST = 'VOUCHER_MINE_LIST_REQUEST';
// export const VOUCHER_MINE_LIST_SUCCESS = 'VOUCHER_MINE_LIST_SUCCESS';
// export const VOUCHER_MINE_LIST_FAIL = 'VOUCHER_MINE_LIST_FAIL';

// export const VOUCHER_EXPORT_REQUEST = 'VOUCHER_EXPORT_REQUEST';
// export const VOUCHER_EXPORT_SUCCESS = 'VOUCHER_EXPORT_SUCCESS';
// export const VOUCHER_EXPORT_FAIL = 'VOUCHER_EXPORT_FAIL';
