export const CATE_LIST = 'CATE_LIST';
export const SET_CATE = 'SET_CATE';

export const CATE_STATUS_REQUEST = 'CATE_STATUS_REQUEST';
export const CATE_STATUS_SUCCESS = 'CATE_STATUS_SUCCESS';
export const CATE_STATUS_FAIL = 'CATE_STATUS_FAIL';
export const CATE_STATUS_RESET = 'CATE_STATUS_RESET';

export const CATE_DELETE_REQUEST = 'CATE_DELETE_REQUEST';
export const CATE_DELETE_SUCCESS = 'CATE_DELETE_SUCCESS';
export const CATE_DELETE_FAIL = 'CATE_DELETE_FAIL';
export const CATE_DELETE_RESET = 'CATE_DELETE_RESET';

export const CATE_DESTROY_REQUEST = 'CATE_DESTROY_REQUEST';
export const CATE_DESTROY_SUCCESS = 'CATE_DESTROY_SUCCESS';
export const CATE_DESTROY_FAIL = 'CATE_DESTROY_FAIL';
export const CATE_DESTROY_RESET = 'CATE_DESTROY_RESET';

export const CATE_RESTORE_REQUEST = 'CATE_RESTORE_REQUEST';
export const CATE_RESTORE_SUCCESS = 'CATE_RESTORE_SUCCESS';
export const CATE_RESTORE_FAIL = 'CATE_RESTORE_FAIL';
export const CATE_RESTORE_RESET = 'CATE_RESTORE_RESET';
