export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_STATUS_REQUEST = 'ORDER_STATUS_REQUEST';
export const ORDER_STATUS_SUCCESS = 'ORDER_STATUS_SUCCESS';
export const ORDER_STATUS_FAIL = 'ORDER_STATUS_FAIL';
export const ORDER_STATUS_RESET = 'ORDER_STATUS_RESET';

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_MINE_LIST_REQUEST = 'ORDER_MINE_LIST_REQUEST';
export const ORDER_MINE_LIST_SUCCESS = 'ORDER_MINE_LIST_SUCCESS';
export const ORDER_MINE_LIST_FAIL = 'ORDER_MINE_LIST_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_LIST_TRASH_REQUEST = 'ORDER_LIST_TRASH_REQUEST';
export const ORDER_LIST_TRASH_SUCCESS = 'ORDER_LIST_TRASH_SUCCESS';
export const ORDER_LIST_TRASH_FAIL = 'ORDER_LIST_TRASH_FAIL';

export const ORDER_EXPORT_REQUEST = 'ORDER_EXPORT_REQUEST';
export const ORDER_EXPORT_SUCCESS = 'ORDER_EXPORT_SUCCESS';
export const ORDER_EXPORT_FAIL = 'ORDER_EXPORT_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';

export const ORDER_DESTROY_REQUEST = 'ORDER_DESTROY_REQUEST';
export const ORDER_DESTROY_SUCCESS = 'ORDER_DESTROY_SUCCESS';
export const ORDER_DESTROY_FAIL = 'ORDER_DESTROY_FAIL';
export const ORDER_DESTROY_RESET = 'ORDER_DESTROY_RESET';

export const ORDER_RESTORE_REQUEST = 'ORDER_RESTORE_REQUEST';
export const ORDER_RESTORE_SUCCESS = 'ORDER_RESTORE_SUCCESS';
export const ORDER_RESTORE_FAIL = 'ORDER_RESTORE_FAIL';
export const ORDER_RESTORE_RESET = 'ORDER_RESTORE_RESET';
