export const PAGES_LIST = 'PAGES_LIST';
export const SET_PAGE = 'SET_PAGE';

export const PAGE_STATUS_REQUEST = 'PAGE_STATUS_REQUEST';
export const PAGE_STATUS_SUCCESS = 'PAGE_STATUS_SUCCESS';
export const PAGE_STATUS_FAIL = 'PAGE_STATUS_FAIL';
export const PAGE_STATUS_RESET = 'PAGE_STATUS_RESET';

export const PAGE_DELETE_REQUEST = 'PAGE_DELETE_REQUEST';
export const PAGE_DELETE_SUCCESS = 'PAGE_DELETE_SUCCESS';
export const PAGE_DELETE_FAIL = 'PAGE_DELETE_FAIL';
export const PAGE_DELETE_RESET = 'PAGE_DELETE_RESET';

export const PAGE_DESTROY_REQUEST = 'PAGE_DESTROY_REQUEST';
export const PAGE_DESTROY_SUCCESS = 'PAGE_DESTROY_SUCCESS';
export const PAGE_DESTROY_FAIL = 'PAGE_DESTROY_FAIL';
export const PAGE_DESTROY_RESET = 'PAGE_DESTROY_RESET';

export const PAGE_RESTORE_REQUEST = 'PAGE_RESTORE_REQUEST';
export const PAGE_RESTORE_SUCCESS = 'PAGE_RESTORE_SUCCESS';
export const PAGE_RESTORE_FAIL = 'PAGE_RESTORE_FAIL';
export const PAGE_RESTORE_RESET = 'PAGE_RESTORE_RESET';
