export const PRODUCTS_LIST = 'PRODUCTS_LIST';
export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH';
export const COLORS_LIST = 'COLORS_LIST';
export const SIZES_LIST = 'SIZES_LIST';

export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_COLOR = 'SET_COLOR';
export const SET_SIZE = 'SET_SIZE';

export const PRODUCT_REVIEW_CREATE_REQUEST = 'PRODUCT_REVIEW_CREATE_REQUEST';
export const PRODUCT_REVIEW_CREATE_SUCCESS = 'PRODUCT_REVIEW_CREATE_SUCCESS';
export const PRODUCT_REVIEW_CREATE_FAIL = 'PRODUCT_REVIEW_CREATE_FAIL';
export const PRODUCT_REVIEW_CREATE_RESET = 'PRODUCT_REVIEW_CREATE_RESET';

export const PRODUCT_MARK_ALL_REQUEST = 'PRODUCT_MARK_ALL_REQUEST';
export const PRODUCT_MARK_ALL_SUCCESS = 'PRODUCT_MARK_ALL_SUCCESS';
export const PRODUCT_MARK_ALL_FAIL = 'PRODUCT_MARK_ALL_FAIL';
export const PRODUCT_MARK_ALL_RESET = 'PRODUCT_MARK_ALL_RESET';

export const PRODUCT_STATUS_REQUEST = 'PRODUCT_STATUS_REQUEST';
export const PRODUCT_STATUS_SUCCESS = 'PRODUCT_STATUS_SUCCESS';
export const PRODUCT_STATUS_FAIL = 'PRODUCT_STATUS_FAIL';
export const PRODUCT_STATUS_RESET = 'PRODUCT_STATUS_RESET';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

export const PRODUCT_DESTROY_REQUEST = 'PRODUCT_DESTROY_REQUEST';
export const PRODUCT_DESTROY_SUCCESS = 'PRODUCT_DESTROY_SUCCESS';
export const PRODUCT_DESTROY_FAIL = 'PRODUCT_DESTROY_FAIL';
export const PRODUCT_DESTROY_RESET = 'PRODUCT_DESTROY_RESET';

export const PRODUCT_RESTORE_REQUEST = 'PRODUCT_RESTORE_REQUEST';
export const PRODUCT_RESTORE_SUCCESS = 'PRODUCT_RESTORE_SUCCESS';
export const PRODUCT_RESTORE_FAIL = 'PRODUCT_RESTORE_FAIL';
export const PRODUCT_RESTORE_RESET = 'PRODUCT_RESTORE_RESET';

export const COLOR_DELETE_REQUEST = 'COLOR_DELETE_REQUEST';
export const COLOR_DELETE_SUCCESS = 'COLOR_DELETE_SUCCESS';
export const COLOR_DELETE_FAIL = 'COLOR_DELETE_FAIL';
export const COLOR_DELETE_RESET = 'COLOR_DELETE_RESET';

export const COLOR_DESTROY_REQUEST = 'COLOR_DESTROY_REQUEST';
export const COLOR_DESTROY_SUCCESS = 'COLOR_DESTROY_SUCCESS';
export const COLOR_DESTROY_FAIL = 'COLOR_DESTROY_FAIL';
export const COLOR_DESTROY_RESET = 'COLOR_DESTROY_RESET';

export const COLOR_RESTORE_REQUEST = 'COLOR_RESTORE_REQUEST';
export const COLOR_RESTORE_SUCCESS = 'COLOR_RESTORE_SUCCESS';
export const COLOR_RESTORE_FAIL = 'COLOR_RESTORE_FAIL';
export const COLOR_RESTORE_RESET = 'COLOR_RESTORE_RESET';

export const SIZE_DELETE_REQUEST = 'SIZE_DELETE_REQUEST';
export const SIZE_DELETE_SUCCESS = 'SIZE_DELETE_SUCCESS';
export const SIZE_DELETE_FAIL = 'SIZE_DELETE_FAIL';
export const SIZE_DELETE_RESET = 'SIZE_DELETE_RESET';

export const SIZE_DESTROY_REQUEST = 'SIZE_DESTROY_REQUEST';
export const SIZE_DESTROY_SUCCESS = 'SIZE_DESTROY_SUCCESS';
export const SIZE_DESTROY_FAIL = 'SIZE_DESTROY_FAIL';
export const SIZE_DESTROY_RESET = 'SIZE_DESTROY_RESET';

export const SIZE_RESTORE_REQUEST = 'SIZE_RESTORE_REQUEST';
export const SIZE_RESTORE_SUCCESS = 'SIZE_RESTORE_SUCCESS';
export const SIZE_RESTORE_FAIL = 'SIZE_RESTORE_FAIL';
export const SIZE_RESTORE_RESET = 'SIZE_RESTORE_RESET';
