export const TOPIC_LIST = 'TOPIC_LIST';
export const SET_TOPIC = 'SET_TOPIC';

export const TOPIC_STATUS_REQUEST = 'TOPIC_STATUS_REQUEST';
export const TOPIC_STATUS_SUCCESS = 'TOPIC_STATUS_SUCCESS';
export const TOPIC_STATUS_FAIL = 'TOPIC_STATUS_FAIL';
export const TOPIC_STATUS_RESET = 'TOPIC_STATUS_RESET';

export const TOPIC_DELETE_REQUEST = 'TOPIC_DELETE_REQUEST';
export const TOPIC_DELETE_SUCCESS = 'TOPIC_DELETE_SUCCESS';
export const TOPIC_DELETE_FAIL = 'TOPIC_DELETE_FAIL';
export const TOPIC_DELETE_RESET = 'TOPIC_DELETE_RESET';

export const TOPIC_DESTROY_REQUEST = 'TOPIC_DESTROY_REQUEST';
export const TOPIC_DESTROY_SUCCESS = 'TOPIC_DESTROY_SUCCESS';
export const TOPIC_DESTROY_FAIL = 'TOPIC_DESTROY_FAIL';
export const TOPIC_DESTROY_RESET = 'TOPIC_DESTROY_RESET';

export const TOPIC_RESTORE_REQUEST = 'TOPIC_RESTORE_REQUEST';
export const TOPIC_RESTORE_SUCCESS = 'TOPIC_RESTORE_SUCCESS';
export const TOPIC_RESTORE_FAIL = 'TOPIC_RESTORE_FAIL';
export const TOPIC_RESTORE_RESET = 'TOPIC_RESTORE_RESET';
